### ISSUE TITLE
round requested bulk and float voltages

### ISSUE THREAD

**Issue by octane321** [Sleeper85/esphome-jk-bms-can#13] opened 2024-02-02 10:19 UTC
is there a way to get rid of the decimals on values from Float and Bulk voltage?
Values should be 56.2V and 55.2V in this example

![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/45717549/9945d1d4-f1da-4468-9d49-0f6b08396099)

I could not find a filter or stock setting to fix this - any idea?
(This is just a cosmetic issue)

**Comment by Sleeper85** [comment] 2024-02-04 08:49
Hi,

From what I understand, these are values that were modified by the slider?
How many decimals do you see just after starting the ESP32 without changing them with the slider?

**Comment by octane321** [comment] 2024-02-04 10:37
the values are right after a restart of the ESP (untouched) - you can also see these values in the webUI if you switch from slider to box

**Comment by luckylinux** [comment] 2024-03-26 14:20
> the values are right after a restart of the ESP (untouched) - you can also see these values in the webUI if you switch from slider to box

I can observe the same issue ... Float/Bulk Voltage slider has like 5 decimals.

For a "Sensor" type component you either could use `round` or `accuracy_decimals`:
https://esphome.io/components/sensor/index.html

For Number it's more complicated. I'm definitively not an ESPHome expert, but what about using a lamba and round(1) ?
https://esphome.io/components/number/#number-on-value

Maybe like in one of the posts here ?
https://community.home-assistant.io/t/solved-use-filter-with-maximum-value/426872

**Comment by shvmm** [comment] 2024-04-05 08:02
Highly likely a well known REST API issue.

Relavant issue on esphome repo.
https://github.com/esphome/esphome-webserver/pull/57

This issue can be safely closed.

**Comment by luckylinux** [comment] 2024-04-05 13:53
Not sure if the esphome-webserver fix solves the issues in Home Assistant as well though.

@shvmm Do you have more details ? 

And when will this be "available" when building the `esphome-jk-bms-can` project ? I'm currently running ESPHome 2023.12.5 so it's definitively lagging behind. Is the ESPHome version (installed via `pip`) lagging so much behind ? Or a specific version of ESPHome is "pinned" either by `esphome-jk-bms-can` or syssi `esphome-jk-bms` ?

**Comment by shvmm** [comment] 2024-04-05 14:51
As far as I am aware, home assistant isn't affected by this issue.

**Comment by luckylinux** [comment] 2024-04-05 14:52
> As far as I am aware, home assistant isn't affected by this issue.

Oh yeah, I am seing 5-6 decimals for float / bulk voltages etc.

**Comment by Sleeper85** [comment] 2024-07-18 06:27
Can I close this issue ?

**Comment by luckylinux** [comment] 2024-07-18 06:37
@Sleeper85 I still see 5 decimals in the "sliding Bar" (Settings e.g. for Bulk/Float Voltage), so I would say the Issue is not solved. You can argue it's not the "fault" of your Code though, it's probably some upstream (Home Assistant and/or ESPHome) Issue.

**Comment by Sleeper85** [comment] 2024-07-18 07:26
ESPhome 2024.7.0 and YamBMS 1.4.1

![image](https://github.com/user-attachments/assets/27f24eda-feb2-4b5c-945e-2f4c6c4b9ff8)

**Comment by luckylinux** [comment] 2024-07-18 07:36
That's not Home Assistant, it's the Web Server (which I disabled to avoid further Hangups on the ESP32).

![image](https://github.com/user-attachments/assets/623b8cf5-10f7-4abb-b822-4a2175e16179)

Home Assistant 2024.6.1 and ESPHome 2024.5.0 if that Helps ...
![image](https://github.com/user-attachments/assets/c8ccc25c-0c15-44d1-b857-4826e75b4c44)

**Comment by Sleeper85** [comment] 2024-07-18 08:01
> ESPhome 2024.7.0 and YamBMS 1.4.1
> 
> ![image](https://private-user-images.githubusercontent.com/153944466/349856036-27f24eda-feb2-4b5c-945e-2f4c6c4b9ff8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODk5NDAsIm5iZiI6MTcyMTI4OTY0MCwicGF0aCI6Ii8xNTM5NDQ0NjYvMzQ5ODU2MDM2LTI3ZjI0ZWRhLWZlYjItNGI1Yy05NDVlLTJmNGM2YzRiOWZmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwODAwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODcwMjZhOWFlNDQ2M2ZiZWVhYjBiMGE4ZmU1YjRiZDZhYTI0YmNmMjM5Y2RhNGJlOGM2MDBiNzJkZGY0NzljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MGGWP7ZuaYCA7tzFWKZIp5YGzJjtRTCjJpE5XrXXKUw)

@luckylinux

It's a Web server screenshot.

**Closed** 2024-07-24 06:59 UTC
